// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pharma-app/Cart.tsx": () => import("../components/mockups/pharma-app/Cart.tsx"),
  "./components/mockups/pharma-app/Categories.tsx": () => import("../components/mockups/pharma-app/Categories.tsx"),
  "./components/mockups/pharma-app/Checkout.tsx": () => import("../components/mockups/pharma-app/Checkout.tsx"),
  "./components/mockups/pharma-app/Home.tsx": () => import("../components/mockups/pharma-app/Home.tsx"),
  "./components/mockups/pharma-app/Login.tsx": () => import("../components/mockups/pharma-app/Login.tsx"),
  "./components/mockups/pharma-app/Orders.tsx": () => import("../components/mockups/pharma-app/Orders.tsx"),
  "./components/mockups/pharma-app/ProductDetail.tsx": () => import("../components/mockups/pharma-app/ProductDetail.tsx"),
  "./components/mockups/pharma-app/Products.tsx": () => import("../components/mockups/pharma-app/Products.tsx"),
  "./components/mockups/pharma-app/Profile.tsx": () => import("../components/mockups/pharma-app/Profile.tsx"),
  "./components/mockups/pharma-app/Splash.tsx": () => import("../components/mockups/pharma-app/Splash.tsx")
};
